{
	"character":{
    	"yys":"阴阳杀",
    	"ding":"定",
    	"wanshi":"万世神兽",
    	"luanshijiaren":"乱世佳人",
    	"TLP":"塔罗牌",
    	"naihehualuo":"奈何花落",
    	"wushuangsha":"无双杀",
    	"ljyhsl":"雷金阴洪石乐",
    	"nyhzrlj":"英魂之刃联机",
    	"xlsh":"希腊神话",
    	"aljx":"奥拉·镜像",
    	"bing":"士兵",
    	"sesx":"十二生肖",
    	"mengzhanc":"萌战competition",
    	"mrfz":"明日方舟",
    	"bwp":"百闻牌",
    	"djl":"刀剑录",
    	"c_zx":"杂项",
    	"tqk":"天气亏",
    	"ywtptjqdfyll":"MAPLE"
    },
	"card":{
    	"shenghen":"圣痕",
    	"bwp_cards":"百闻牌"
    },
	"mode":{
    	"partner":"成对模式",
    	"kzsg":"卡战三国",
    	"wzzz":"王者之战",
    	"wjms":"无尽模式",
    	"aolaStar":"奥拉星"
    },
	"submode":{
    	"bingjingliangzu":"兵精粮足",
    	"jiangshimoshi":"僵尸模式",
    	"jianbingmoshi":"兼并模式",
    	"dbzz":"带兵作战",
    	"lingzhan":"灵战",
    	"qxhz":"群雄混战",
    	"gcms":"攻城模式",
    	"ssbx":"杀上保下",
    	"lsww":"乱世称王",
    	"ysws":"有杀无闪",
    	"lswz":"乱世王者",
    	"kzol_lucky":"幸运666",
    	"sanyingmoshi":"三英模式"
    },
	"challenge":{
    	"boss":"boss"
    },
	"content_function":{
    	"menu":"菜单",
    	"task":"任务",
    	"bag":"背包",
    	"djsl":"单将胜率",
    	"repair":"修复原版BUG",
    	"jywj":"禁用武将",
    	"zgcj":"战功成就",
    	"bw":"宝物",
    	"jswj":"解锁武将",
    	"skillSkin":"技能皮肤",
    	"wjhc":"武将合成",
    	"kzsg1":"卡战三国图鉴",
    	"ldmsxx":"乱斗模式选项",
    	"ALX":"奥拉星S",
    	"ckdt":"查看大图",
		"animation":"插件与特效",
    	"skillButton":"技能按钮"
    },
	"precontent_function":{
    	"wjbll":"武将包浏览",
    	"jmsf":"界面缩放",
    	"modeOL":"联机模式",
    	"basis":"基本主代码",
    	"ts":"提示（game.say函数）",
    	"load_NY":"查看加载内容",
    	"other_extension":"扩展ol本体更新",
    	"weather":"天气系统",
    	"zyxjgd":"自由选将改动"
    }
}