window.func=function(lib,game,ui,get,ai,_status){
	lib.mode.partner.config.kzol_weather={
		name:'天气变化',
		init:false,
		restart:true,
		frequent:true,
	};
	lib.mode.wjms.config.kzol_weather={
		name:'天气变化',
		init:false,
		restart:true,
		frequent:true,
	};
	lib.mode.wangzhezhizhan.config.kzol_weather={
		name:'天气变化',
		init:false,
		restart:true,
		frequent:true,
	};
	lib.mode.kzsg.config.kzol_weather={
		name:'天气变化',
		init:false,
		restart:true,
		frequent:true,
	};
}